<?php
$version = 'v1.0';
$pagedata = array(
    'useradmin' => array(
        'title_1' => 'ผู้ใช้งานเว็บ',
        'description' => 'เพิ่มผู้ใช้งานเว็บไชต์ของคุณ',
        'filename' => 'lp_useradmin.php',
        'menu_name' => 'User Admin ผู้ใช้งานเว็บ'),
    'setting' => array(
        'title_1' => 'ตั้งค่าเว็บ',
        'description' => 'ตั้งค่าเว็บไชต์ของคุณที่นี้',
        'filename' => 'lp_setting.php',
        'menu_name' => 'Setting Website ตั้งค่าเว็บไชต์ของคุณ'),
    'page' => array(
        'title_1' => 'เพิ่มหน้าเว็บ',
        'description' => 'สร้างหน้าเว็บหรือหน้าส่งเสริมการขายของตัวเองที่นี้',
        'filename' => 'lp_page.php',
        'menu_name' => 'Page Menu Website เพิ่มหน้าสำหรับติดต่อหรือโปรโมท'),
    'sub_page' => array(
        'title_1' => 'เพิ่มหน้าเว็บส่วนเสริม',
        'description' => 'สร้างหน้าเว็บส่วนเสริมหรือหน้าส่งเสริมการขายของตัวเองที่นี้',
        'filename' => 'lp_sub_page.php',
        'menu_name' => 'Sub Page Menu Website เพิ่มหน้าสำหรับติดต่อหรือโปรโมท'),
    /*'portfolio' => array(
        'title_1' => 'Tip & Details',
        'description' => 'รายละเอียด',
        'filename' => 'lp_portfolio.php',
        'menu_name' => 'Tip & Details: รายละเอียด'),
    'videos' => array(
        'title_1' => 'เพิ่มวิดีโอผลงาน',
        'description' => 'เพิ่มผลงานที่เป็นวิดีโอได้จากที่นี้',
        'filename' => 'lp_video.php',
        'menu_name' => 'Portfolio Video Page วิดีโอของผลงานที่ทำมา'),*/
    'news' => array(
        'title_1' => 'เพิ่มข่าวสาร',
        'description' => 'เพิ่มข่าวสารทั่วไปของเว็บได้ที่นี้',
        'filename' => 'lp_news.php',
        'menu_name' => 'News Page ข่าวสารต่างๆของเว็บ'),
    'slideshow' => array(
        'title_1' => 'เพิ่มภาพสไลต์',
        'description' => 'เพิ่มภาพสไลด์ในหัวเว็บ เพื่อโปรโมทสินค้าและบริการของคุณ',
        'filename' => 'lp_slidshow.php',
        'menu_name' => 'Slide Show ภาพสไลด์ในหัวเว็บ'),
    /*'event' => array(
        'title_1' => 'เพิ่มรูปงานที่เคยทำ',
        'description' => 'เพิ่มรูปภาพผลงานกิจกรรม ที่เคยทำมา จะนำไปแสดงในหน้าแรก',
        'filename' => 'lp_event.php',
        'menu_name' => 'Event รูปภาพกิจกรรม'),
    'ads' => array(
        'title_1' => 'เพิ่มโฆษณา',
        'description' => 'เพิ่มโฆษณาของตัวเองหรือโปรโมชั่นและคำรับทำงานหรืออื่นๆ',
        'filename' => 'lp_ads.php',
        'menu_name' => 'Ads เพิ่มโฆษณา'),*/
    'default' => array(
        'title_1' => 'ข้อความติดต่อ',
        'description' => 'ข้อความติดต่อจากลูกค้าถึงเรา',
        'filename' => 'lp_mail.php',
        'menu_name' => 'Mail ข้อความติดต่อ'),
    'customer' => array(
        'title_1' => 'ลูกค้า',
        'description' => 'ลูกค้า',
        'filename' => 'customer.php',
        'menu_name' => 'Customer ลูกค้า'),
    'Active License' => array(
        'title_1' => 'Active License',
        'description' => 'Active License',
        'filename' => 'active_license.php',
        'menu_name' => 'Active License'),
    'Product Active License' => array(
        'title_1' => 'Product Active License',
        'description' => 'Product Active License',
        'filename' => 'active_product.php',
        'menu_name' => 'Product Active License'),
    'Files' => array(
        'title_1' => 'File & Download',
        'description' => 'Files & Downloads',
        'filename' => 'file_upload.php',
        'menu_name' => 'File & Download'),
    'logout' => array(
        'title_1' => 'ออกจากระบบ',
        'description' => 'ออกจากระบบ',
        'filename' => 'lp_logout.php',
        'menu_name' => 'ออกจากระบบ')
    );
?>